# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_12.5.app/Contents/Developer # Adjust Xcode version if needed
        sudo xcodebuild -version # Verify Xcode version

    - name: Build the project
      run: |
        xcodebuild -scheme YourSchemeName -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' clean build

    - name: Run tests
      run: |
        xcodebuild test -scheme YourSchemeName -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' | xcpretty
