# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the project
      run: |
        xcodebuild -scheme listAppS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' clean build

    - name: Run tests
      run: |
        xcodebuild test -scheme listAppS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' | xcpretty
